# name: Sync Upstream

# on:
#   schedule:
#     - cron: '0 2 * * *'   # Every day at 2:00 AM UTC (7:00 AM PST)
#   workflow_dispatch:

# jobs:
#   sync:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v3

#       - name: Set Up Git
#         run: |
#           git config user.name "github-actions[bot]"
#           git config user.email "github-actions[bot]@users.noreply.github.com"

#       - name: Add Upstream Remote
#         run: |
#           if git remote | grep -q upstream; then
#             echo "Upstream already exists"
#           else
#             git remote add upstream https://github.com/HKUDS/LightRAG.git
#           fi

#       - name: Fetch Upstream
#         run: |
#           git fetch upstream

#       - name: Merge with Conflict Resolution
#         run: |
#           git checkout main
#           # Attempt auto-merge, preferring upstream changes
#           git merge upstream/main -X theirs || true

#       - name: Ensure Workflow File is Present
#         run: |
#           mkdir -p .github/workflows
#           echo "Ensuring sync-upstream.yml is present"
#           cat <<EOF > .github/workflows/sync-upstream.yml
#           name: Sync Upstream

#           on:
#             schedule:
#               - cron: '0 2 * * *'
#             workflow_dispatch:

#           jobs:
#             sync:
#               runs-on: ubuntu-latest
#               steps:
#                 - name: Checkout Repository
#                   uses: actions/checkout@v3

#                 - name: Set Up Git
#                   run: |
#                     git config user.name "github-actions[bot]"
#                     git config user.email "github-actions[bot]@users.noreply.github.com"

#                 - name: Fetch and Merge
#                   run: |
#                     git fetch upstream
#                     git checkout main
#                     git merge upstream/main -X theirs || true

#                 - name: Push Changes
#                   run: |
#                     git push origin main
#           EOF

#       - name: Push Changes
#         run: |
#           git add .github/workflows/sync-upstream.yml
#           git commit -m "Ensure sync-upstream.yml is present after sync"
#           git push origin main
