name: Sync Upstream

on:
  schedule:
    - cron: '15 1 * * *'  # Every day at 1:15 AM UTC (6:15 AM PST)
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add Upstream Remote
        run: |
          # Check if upstream already exists
          if git remote | grep -q upstream; then
            echo "Upstream already exists"
          else
            git remote add upstream https://github.com/HKUDS/LightRAG.git
          fi

      - name: Fetch and Merge
        run: |
          git fetch upstream
          git checkout main
          git merge --ff-only upstream/main

      - name: Push Changes
        run: |
          git push origin main
